### ISSUE TITLE
Cheat won't display

### ISSUE THREAD

**Issue by cxxch** [exploitmafia/singlefile#12]
Pretty much I built the dll in x86 no problems, and when I inject it into csgo nothing happens? INS won't open anything. I use sazinjector.

**Comment by exploitmafia** [comment]
Does a console appear? I'm not sure what "Sazinjector" is, however it may be using LoadLibrary to inject, something that CS:GO no longer supports.

**Comment by cxxch** [comment]
No a console does not appear and SazInjector uses Loadlibrary but it also has the option of manual map, I have tried injecting the dll using manual map and it seems to crash the game? (For me atleast injecting osiris using LoadLibrary works)

**Comment by es3n1n** [comment]
It seems that your injector isn't working properly. Try with [Xenos](https://github.com/DarthTon/Xenos/releases/tag/2.3.2).

**Comment by cxxch** [comment]
I just tried to Inject the dll I built and I got this error message. 

https://user-images.githubusercontent.com/64287127/116277484-81fe8f80-a753-11eb-9994-23688be23b6a.png

**Comment by es3n1n** [comment]
@cxxch this error means that injector can't load some deps, it may occur because of unfixed loadlibrary injection method, you need to use smth like [this](https://github.com/danielkrupinski/OneByteLdr/blob/master/OneByteLdr.py) or patch it by yourself if you still want to use a loadlibrary injection method.
Compiled latest version and injected using default xenos settings.
![img](https://i.imgur.com/5Fzh6jY.png)


upd: made a very simple lla injector, you can use [it](https://gist.github.com/es3n1n/cbfa18457fd3e6fa30c6f40a48fa4321)

**Comment by exploitmafia** [comment]
I can confirm that es3n1n's injector works perfectly, so thanks for that. If you inject with Xenos or build his and it still doesn't work, try installing these redistributables, but I highly suspect that is not the case, but that you are using an improper injector that Xenos or his will fix.

x86 & x64 MSVC 2015-2019 Redistributibles:

[x86](https://aka.ms/vs/16/release/vc_redist.x86.exe)
[x64](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by exploitmafia** [comment]
Fixed in #14.
